### ISSUE TITLE
Crash in android 6 while opening file

### ISSUE THREAD

**Issue by Gamer750** [edeso/bubble2#5]

**Comment by edeso** [comment]
not really actively supporting android before 8 anymore. still if you provide a sample file i might have a look.

**Comment by Gamer750** [comment]
> not really actively supporting android before 8 anymore. still if you provide a sample file i might have a look.

It is a manhwa

**Comment by edeso** [comment]
should be fixed. please try https://get.hidrive.com/RJgoYXm9 and post your result.

also removed is the enforced rescale so your vertical strips should look much better now.

**Comment by Gamer750** [comment]
It is showing 
![Screenshot_20231107-214034_1](https://github.com/edeso/bubble2/assets/141329708/c9e85f5a-930e-4326-8528-b6ece65444e4)

The device is bit old it is android 6

**Comment by edeso** [comment]
hmm, ok. try this one https://files.fm/u/gtvprbbvje . tested this and it installs.

**Comment by Gamer750** [comment]
> hmm, ok. try this one https://files.fm/u/gtvprbbvje . tested this and it installs.

It is working

**Comment by edeso** [comment]
thanks! will be fixed in the next release.

**Comment by edeso** [comment]
v2.4.2 containing the fix was just released.
